name: x05  c++ CI

on:
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Compile C++ 2017
       run: g++ test.cpp -std=c++17 -o test
    
